version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=reallyStrongPwd123!
      - MSSQL_PID=Developer
    ports:
      - "11433:1433"
    # healthcheck:  # <- komple kaldırıyoruz
    #   test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'reallyStrongPwd123!' -Q 'SELECT 1' || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 30

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"

  api:
    build:
      context: .
      dockerfile: NetCaseStudy.Api/Dockerfile
    depends_on:
      sqlserver:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderSystemDatabase;User Id=sa;Password=reallyStrongPwd123;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - MIGRATE_ON_STARTUP=true
    ports:
      - "8080:8080"
